version: '3.5'

services:
  phps:
    # The official v2.0 Traefik docker image
    image: testapps/phps:latest
    networks:
      - web
    labels:
      - "traefik.http.routers.phps.rule=Host(`test-apps3.mytestapp.com`)"

networks:
  web:
    external:
      name: traefik_default
